package world

// SuperflatGroundY is the Y coordinate of the top solid block generated by the
// built-in superflat generator. Java and Bedrock protocol adapters must use
// this same value or clients will see different terrain/player heights.
const SuperflatGroundY = 3

// SuperflatSpawnY is the player's feet Y coordinate when standing on the
// superflat surface.
const SuperflatSpawnY = SuperflatGroundY + 1
