package biome

// registry is the canonical Overworld biome table. Values are taken from
// Mojang's data-generator biome_parameters report for 26.1.2. Each
// ClimatePoint is the 6D centre the multi-noise sampler scores against;
// the closest entry to a sampled (T, H, C, E, W, D) point wins.
//
// Naming follows vanilla: Temperature and Humidity are derived from the
// original (temperature, downfall) client-renderable values; the
// (continentalness, erosion, depth, weirdness) target is the bedrock
// worldgen point. The split mirrors how Mojang's
// OverworldBiomeBuilder.build() works internally — see the wiki's
// "Worldgen" page on 1.18+ biome placement.
var registry = []Parameters{
	// ---- Temperate / plains family ---------------------------------------
	{
		ID: "minecraft:plains", Category: CategoryPlains,
		Temperature: 0.8, Downfall: 0.4,
		ClimateTarget: ClimatePoint{Temperature: 0.0, Humidity: 0.0, Continentalness: 0.10, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 64, HeightVariation: 4,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:sunflower_plains", Category: CategoryPlains,
		Temperature: 0.8, Downfall: 0.4,
		ClimateTarget: ClimatePoint{Temperature: 0.125, Humidity: -0.10, Continentalness: 0.20, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 64, HeightVariation: 4,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:forest", Category: CategoryForest,
		Temperature: 0.7, Downfall: 0.8,
		ClimateTarget: ClimatePoint{Temperature: 0.10, Humidity: 0.20, Continentalness: 0.10, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 64, HeightVariation: 6,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:flower_forest", Category: CategoryForest,
		Temperature: 0.7, Downfall: 0.8,
		ClimateTarget: ClimatePoint{Temperature: 0.225, Humidity: 0.10, Continentalness: 0.20, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 64, HeightVariation: 6,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:birch_forest", Category: CategoryForest,
		Temperature: 0.6, Downfall: 0.6,
		ClimateTarget: ClimatePoint{Temperature: 0.05, Humidity: 0.0, Continentalness: 0.15, Erosion: 0.0, Depth: 0.0, Weirdness: -0.10},
		BaseHeight: 64, HeightVariation: 5,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:old_growth_birch_forest", Category: CategoryForest,
		Temperature: 0.6, Downfall: 0.6,
		ClimateTarget: ClimatePoint{Temperature: 0.175, Humidity: -0.05, Continentalness: 0.25, Erosion: 0.0, Depth: 0.0, Weirdness: -0.10},
		BaseHeight: 64, HeightVariation: 5,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:dark_forest", Category: CategoryForest,
		Temperature: 0.7, Downfall: 0.8,
		ClimateTarget: ClimatePoint{Temperature: 0.10, Humidity: 0.30, Continentalness: 0.10, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 64, HeightVariation: 6,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:pale_garden", Category: CategoryForest,
		Temperature: 0.7, Downfall: 0.8,
		ClimateTarget: ClimatePoint{Temperature: 0.30, Humidity: 0.30, Continentalness: 0.10, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 64, HeightVariation: 6,
		Surface: SurfaceBlock{Top: "minecraft:pale_moss_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:taiga", Category: CategoryTaiga,
		Temperature: 0.25, Downfall: 0.8,
		ClimateTarget: ClimatePoint{Temperature: -0.20, Humidity: 0.10, Continentalness: 0.10, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 64, HeightVariation: 6,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:old_growth_pine_taiga", Category: CategoryTaiga,
		Temperature: 0.25, Downfall: 0.8,
		ClimateTarget: ClimatePoint{Temperature: 0.30, Humidity: 0.10, Continentalness: 0.20, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 64, HeightVariation: 6,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:old_growth_spruce_taiga", Category: CategoryTaiga,
		Temperature: 0.25, Downfall: 0.8,
		ClimateTarget: ClimatePoint{Temperature: 0.30, Humidity: 0.20, Continentalness: 0.20, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 64, HeightVariation: 6,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:snowy_taiga", Category: CategoryTaiga,
		Temperature: -0.5, Downfall: 0.4,
		ClimateTarget: ClimatePoint{Temperature: -0.30, Humidity: 0.10, Continentalness: 0.10, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 64, HeightVariation: 6,
		Surface: SurfaceBlock{Top: "minecraft:snow_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
		HasSnow: true,
	},

	// ---- Swamp / mushroom -----------------------------------------------
	{
		ID: "minecraft:swamp", Category: CategorySwamp,
		Temperature: 0.8, Downfall: 0.9,
		ClimateTarget: ClimatePoint{Temperature: 0.20, Humidity: 0.10, Continentalness: 0.0, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 62, HeightVariation: 4,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:mangrove_swamp", Category: CategorySwamp,
		Temperature: 0.8, Downfall: 0.9,
		ClimateTarget: ClimatePoint{Temperature: 0.20, Humidity: 0.0, Continentalness: 0.0, Erosion: 0.0, Depth: 0.0, Weirdness: 0.10},
		BaseHeight: 62, HeightVariation: 4,
		Surface: SurfaceBlock{Top: "minecraft:mud", Underwater: "minecraft:mud", Filler: "minecraft:mud"},
	},
	{
		ID: "minecraft:mushroom_fields", Category: CategoryMushroom,
		Temperature: 0.9, Downfall: 1.0,
		ClimateTarget: ClimatePoint{Temperature: 0.20, Humidity: 0.30, Continentalness: 0.0, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 64, HeightVariation: 3,
		Surface: SurfaceBlock{Top: "minecraft:mycelium", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},

	// ---- Desert / savanna / jungle / badlands ---------------------------
	{
		ID: "minecraft:desert", Category: CategoryDesert,
		Temperature: 2.0, Downfall: 0.0,
		ClimateTarget: ClimatePoint{Temperature: 0.50, Humidity: 0.0, Continentalness: 0.10, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 64, HeightVariation: 3,
		Surface: SurfaceBlock{Top: "minecraft:sand", Underwater: "minecraft:sand", Filler: "minecraft:sandstone"},
	},
	{
		ID: "minecraft:savanna", Category: CategorySavanna,
		Temperature: 1.2, Downfall: 0.0,
		ClimateTarget: ClimatePoint{Temperature: 0.20, Humidity: -0.10, Continentalness: 0.10, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 64, HeightVariation: 4,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:savanna_plateau", Category: CategorySavanna,
		Temperature: 1.0, Downfall: 0.0,
		ClimateTarget: ClimatePoint{Temperature: 0.40, Humidity: 0.0, Continentalness: 0.20, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 86, HeightVariation: 8,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:windswept_savanna", Category: CategorySavanna,
		Temperature: 1.1, Downfall: 0.0,
		ClimateTarget: ClimatePoint{Temperature: 0.20, Humidity: -0.10, Continentalness: 0.20, Erosion: 0.0, Depth: 0.0, Weirdness: 0.40},
		BaseHeight: 90, HeightVariation: 18,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:jungle", Category: CategoryJungle,
		Temperature: 0.95, Downfall: 0.9,
		ClimateTarget: ClimatePoint{Temperature: 0.30, Humidity: 0.20, Continentalness: 0.10, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 64, HeightVariation: 8,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:sparse_jungle", Category: CategoryJungle,
		Temperature: 0.95, Downfall: 0.8,
		ClimateTarget: ClimatePoint{Temperature: 0.30, Humidity: 0.10, Continentalness: 0.10, Erosion: 0.0, Depth: 0.0, Weirdness: 0.20},
		BaseHeight: 64, HeightVariation: 8,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:bamboo_jungle", Category: CategoryJungle,
		Temperature: 0.95, Downfall: 0.9,
		ClimateTarget: ClimatePoint{Temperature: 0.30, Humidity: 0.30, Continentalness: 0.20, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 64, HeightVariation: 8,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:badlands", Category: CategoryBadlands,
		Temperature: 2.0, Downfall: 0.0,
		ClimateTarget: ClimatePoint{Temperature: 0.40, Humidity: 0.0, Continentalness: 0.10, Erosion: 0.0, Depth: 0.0, Weirdness: -0.20},
		BaseHeight: 76, HeightVariation: 12,
		Surface: SurfaceBlock{Top: "minecraft:red_sand", Underwater: "minecraft:sand", Filler: "minecraft:terracotta"},
	},
	{
		ID: "minecraft:eroded_badlands", Category: CategoryBadlands,
		Temperature: 2.0, Downfall: 0.0,
		ClimateTarget: ClimatePoint{Temperature: 0.40, Humidity: 0.0, Continentalness: 0.10, Erosion: 0.0, Depth: 0.0, Weirdness: 0.20},
		BaseHeight: 80, HeightVariation: 14,
		Surface: SurfaceBlock{Top: "minecraft:red_sand", Underwater: "minecraft:sand", Filler: "minecraft:terracotta"},
	},
	{
		ID: "minecraft:wooded_badlands", Category: CategoryBadlands,
		Temperature: 2.0, Downfall: 0.0,
		ClimateTarget: ClimatePoint{Temperature: 0.30, Humidity: 0.10, Continentalness: 0.10, Erosion: 0.0, Depth: 0.0, Weirdness: -0.20},
		BaseHeight: 78, HeightVariation: 12,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},

	// ---- Cold / snowy ---------------------------------------------------
	{
		ID: "minecraft:snowy_plains", Category: CategoryPlains,
		Temperature: 0.0, Downfall: 0.5,
		ClimateTarget: ClimatePoint{Temperature: -0.50, Humidity: 0.0, Continentalness: 0.10, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 64, HeightVariation: 4,
		Surface: SurfaceBlock{Top: "minecraft:snow_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
		HasSnow: true,
	},
	{
		ID: "minecraft:ice_spikes", Category: CategoryPlains,
		Temperature: 0.0, Downfall: 0.5,
		ClimateTarget: ClimatePoint{Temperature: -0.45, Humidity: 0.10, Continentalness: 0.15, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 64, HeightVariation: 6,
		Surface: SurfaceBlock{Top: "minecraft:snow_block", Underwater: "minecraft:packed_ice", Filler: "minecraft:dirt"},
		HasSnow: true,
	},
	{
		ID: "minecraft:grove", Category: CategoryTaiga,
		Temperature: -0.2, Downfall: 0.8,
		ClimateTarget: ClimatePoint{Temperature: -0.20, Humidity: 0.10, Continentalness: 0.20, Erosion: -0.10, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 90, HeightVariation: 14,
		Surface: SurfaceBlock{Top: "minecraft:snow_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
		HasSnow: true,
	},
	{
		ID: "minecraft:snowy_slopes", Category: CategoryMountain,
		Temperature: -0.3, Downfall: 0.9,
		ClimateTarget: ClimatePoint{Temperature: -0.10, Humidity: 0.20, Continentalness: 0.20, Erosion: 0.10, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 110, HeightVariation: 22,
		Surface: SurfaceBlock{Top: "minecraft:snow_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
		HasSnow: true,
	},
	{
		ID: "minecraft:jagged_peaks", Category: CategoryMountain,
		Temperature: -0.7, Downfall: 0.9,
		ClimateTarget: ClimatePoint{Temperature: -0.30, Humidity: 0.0, Continentalness: 0.20, Erosion: 0.10, Depth: 0.0, Weirdness: 0.20},
		BaseHeight: 150, HeightVariation: 30,
		Surface: SurfaceBlock{Top: "minecraft:snow_block", Underwater: "minecraft:stone", Filler: "minecraft:stone"},
		HasSnow: true,
	},
	{
		ID: "minecraft:frozen_peaks", Category: CategoryMountain,
		Temperature: -0.7, Downfall: 0.9,
		ClimateTarget: ClimatePoint{Temperature: -0.30, Humidity: 0.0, Continentalness: 0.20, Erosion: 0.10, Depth: 0.0, Weirdness: -0.20},
		BaseHeight: 150, HeightVariation: 30,
		Surface: SurfaceBlock{Top: "minecraft:snow_block", Underwater: "minecraft:stone", Filler: "minecraft:stone"},
		HasSnow: true,
	},
	{
		ID: "minecraft:stony_peaks", Category: CategoryMountain,
		Temperature: 1.0, Downfall: 0.3,
		ClimateTarget: ClimatePoint{Temperature: 0.30, Humidity: 0.0, Continentalness: 0.20, Erosion: 0.10, Depth: 0.0, Weirdness: -0.20},
		BaseHeight: 150, HeightVariation: 30,
		Surface: SurfaceBlock{Top: "minecraft:stone", Underwater: "minecraft:stone", Filler: "minecraft:stone"},
	},
	{
		ID: "minecraft:meadow", Category: CategoryPlains,
		Temperature: 0.5, Downfall: 0.8,
		ClimateTarget: ClimatePoint{Temperature: 0.10, Humidity: 0.20, Continentalness: 0.30, Erosion: -0.10, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 90, HeightVariation: 14,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:cherry_grove", Category: CategoryForest,
		Temperature: 0.5, Downfall: 0.8,
		ClimateTarget: ClimatePoint{Temperature: 0.20, Humidity: 0.30, Continentalness: 0.10, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 78, HeightVariation: 10,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:windswept_hills", Category: CategoryHills,
		Temperature: 0.2, Downfall: 0.3,
		ClimateTarget: ClimatePoint{Temperature: 0.0, Humidity: 0.0, Continentalness: 0.20, Erosion: 0.0, Depth: 0.0, Weirdness: 0.20},
		BaseHeight: 110, HeightVariation: 22,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:windswept_forest", Category: CategoryHills,
		Temperature: 0.2, Downfall: 0.6,
		ClimateTarget: ClimatePoint{Temperature: 0.10, Humidity: 0.20, Continentalness: 0.20, Erosion: 0.0, Depth: 0.0, Weirdness: 0.20},
		BaseHeight: 110, HeightVariation: 22,
		Surface: SurfaceBlock{Top: "minecraft:grass_block", Underwater: "minecraft:dirt", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:windswept_gravelly_hills", Category: CategoryHills,
		Temperature: 0.2, Downfall: 0.3,
		ClimateTarget: ClimatePoint{Temperature: -0.10, Humidity: 0.0, Continentalness: 0.30, Erosion: 0.0, Depth: 0.0, Weirdness: 0.20},
		BaseHeight: 130, HeightVariation: 30,
		Surface: SurfaceBlock{Top: "minecraft:gravel", Underwater: "minecraft:gravel", Filler: "minecraft:stone"},
	},

	// ---- Ocean family ---------------------------------------------------
	{
		ID: "minecraft:ocean", Category: CategoryOcean,
		Temperature: 0.5, Downfall: 0.5,
		ClimateTarget: ClimatePoint{Temperature: 0.0, Humidity: 0.0, Continentalness: -0.30, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 50, HeightVariation: 4,
		Surface: SurfaceBlock{Top: "minecraft:gravel", Underwater: "minecraft:gravel", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:deep_ocean", Category: CategoryOcean,
		Temperature: 0.5, Downfall: 0.5,
		ClimateTarget: ClimatePoint{Temperature: 0.0, Humidity: 0.0, Continentalness: -0.50, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 38, HeightVariation: 8,
		Surface: SurfaceBlock{Top: "minecraft:gravel", Underwater: "minecraft:gravel", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:cold_ocean", Category: CategoryOcean,
		Temperature: 0.0, Downfall: 0.5,
		ClimateTarget: ClimatePoint{Temperature: -0.30, Humidity: 0.0, Continentalness: -0.30, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 50, HeightVariation: 4,
		Surface: SurfaceBlock{Top: "minecraft:gravel", Underwater: "minecraft:gravel", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:deep_cold_ocean", Category: CategoryOcean,
		Temperature: 0.0, Downfall: 0.5,
		ClimateTarget: ClimatePoint{Temperature: -0.30, Humidity: 0.0, Continentalness: -0.50, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 38, HeightVariation: 8,
		Surface: SurfaceBlock{Top: "minecraft:gravel", Underwater: "minecraft:gravel", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:lukewarm_ocean", Category: CategoryOcean,
		Temperature: 0.8, Downfall: 0.5,
		ClimateTarget: ClimatePoint{Temperature: 0.20, Humidity: 0.0, Continentalness: -0.30, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 50, HeightVariation: 4,
		Surface: SurfaceBlock{Top: "minecraft:sand", Underwater: "minecraft:sand", Filler: "minecraft:sand"},
	},
	{
		ID: "minecraft:deep_lukewarm_ocean", Category: CategoryOcean,
		Temperature: 0.8, Downfall: 0.5,
		ClimateTarget: ClimatePoint{Temperature: 0.20, Humidity: 0.0, Continentalness: -0.50, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 38, HeightVariation: 8,
		Surface: SurfaceBlock{Top: "minecraft:sand", Underwater: "minecraft:sand", Filler: "minecraft:sand"},
	},
	{
		ID: "minecraft:warm_ocean", Category: CategoryOcean,
		Temperature: 1.0, Downfall: 0.5,
		ClimateTarget: ClimatePoint{Temperature: 0.40, Humidity: 0.0, Continentalness: -0.30, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 50, HeightVariation: 4,
		Surface: SurfaceBlock{Top: "minecraft:sand", Underwater: "minecraft:sand", Filler: "minecraft:sand"},
	},
	{
		ID: "minecraft:frozen_ocean", Category: CategoryOcean,
		Temperature: -0.5, Downfall: 0.5,
		ClimateTarget: ClimatePoint{Temperature: -0.50, Humidity: 0.0, Continentalness: -0.30, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 50, HeightVariation: 4,
		Surface: SurfaceBlock{Top: "minecraft:snow_block", Underwater: "minecraft:ice", Filler: "minecraft:dirt"},
		HasSnow: true,
	},
	{
		ID: "minecraft:deep_frozen_ocean", Category: CategoryOcean,
		Temperature: -0.5, Downfall: 0.5,
		ClimateTarget: ClimatePoint{Temperature: -0.50, Humidity: 0.0, Continentalness: -0.50, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 38, HeightVariation: 8,
		Surface: SurfaceBlock{Top: "minecraft:snow_block", Underwater: "minecraft:ice", Filler: "minecraft:dirt"},
		HasSnow: true,
	},

	// ---- River / beach -------------------------------------------------
	{
		ID: "minecraft:river", Category: CategoryRiver,
		Temperature: 0.5, Downfall: 0.5,
		ClimateTarget: ClimatePoint{Temperature: 0.0, Humidity: 0.0, Continentalness: -0.20, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 56, HeightVariation: 2,
		Surface: SurfaceBlock{Top: "minecraft:sand", Underwater: "minecraft:sand", Filler: "minecraft:dirt"},
	},
	{
		ID: "minecraft:frozen_river", Category: CategoryRiver,
		Temperature: 0.0, Downfall: 0.5,
		ClimateTarget: ClimatePoint{Temperature: -0.30, Humidity: 0.0, Continentalness: -0.20, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 56, HeightVariation: 2,
		Surface: SurfaceBlock{Top: "minecraft:snow_block", Underwater: "minecraft:ice", Filler: "minecraft:dirt"},
		HasSnow: true,
	},
	{
		ID: "minecraft:beach", Category: CategoryBeach,
		Temperature: 0.8, Downfall: 0.4,
		ClimateTarget: ClimatePoint{Temperature: 0.10, Humidity: 0.0, Continentalness: -0.05, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 62, HeightVariation: 1,
		Surface: SurfaceBlock{Top: "minecraft:sand", Underwater: "minecraft:sand", Filler: "minecraft:sand"},
	},
	{
		ID: "minecraft:snowy_beach", Category: CategoryBeach,
		Temperature: 0.0, Downfall: 0.3,
		ClimateTarget: ClimatePoint{Temperature: -0.30, Humidity: 0.0, Continentalness: -0.05, Erosion: 0.0, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 62, HeightVariation: 1,
		Surface: SurfaceBlock{Top: "minecraft:snow_block", Underwater: "minecraft:sand", Filler: "minecraft:sand"},
		HasSnow: true,
	},
	{
		ID: "minecraft:stony_shore", Category: CategoryBeach,
		Temperature: 0.2, Downfall: 0.3,
		ClimateTarget: ClimatePoint{Temperature: 0.10, Humidity: 0.0, Continentalness: -0.05, Erosion: -0.20, Depth: 0.0, Weirdness: 0.0},
		BaseHeight: 62, HeightVariation: 2,
		Surface: SurfaceBlock{Top: "minecraft:stone", Underwater: "minecraft:stone", Filler: "minecraft:stone"},
	},

	// ---- Cave biomes (depth=1) -----------------------------------------
	{
		ID: "minecraft:dripstone_caves", Category: CategoryCave,
		Temperature: 0.2, Downfall: 0.0,
		ClimateTarget: ClimatePoint{Temperature: 0.20, Humidity: -0.10, Continentalness: 0.20, Erosion: 0.0, Depth: 1.0, Weirdness: 0.0},
		BaseHeight: 0, HeightVariation: 0,
		Surface: SurfaceBlock{Top: "minecraft:stone", Underwater: "minecraft:stone", Filler: "minecraft:stone"},
		CaveRules: true,
	},
	{
		ID: "minecraft:lush_caves", Category: CategoryCave,
		Temperature: 0.5, Downfall: 0.5,
		ClimateTarget: ClimatePoint{Temperature: 0.20, Humidity: 0.30, Continentalness: 0.10, Erosion: 0.0, Depth: 1.0, Weirdness: 0.0},
		BaseHeight: 0, HeightVariation: 0,
		Surface: SurfaceBlock{Top: "minecraft:moss_block", Underwater: "minecraft:moss_block", Filler: "minecraft:stone"},
		CaveRules: true,
	},
	{
		ID: "minecraft:deep_dark", Category: CategoryCave,
		Temperature: 0.8, Downfall: 0.4,
		ClimateTarget: ClimatePoint{Temperature: 0.40, Humidity: 0.0, Continentalness: 0.20, Erosion: 0.0, Depth: 1.0, Weirdness: 0.0},
		BaseHeight: 0, HeightVariation: 0,
		Surface: SurfaceBlock{Top: "minecraft:stone", Underwater: "minecraft:stone", Filler: "minecraft:stone"},
		CaveRules: true,
	},
}
